# Generated by Django 5.0.3 on 2024-03-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
